server:
  port: 0
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ssafyartrendpjt


spring:
  #  sql:
  #    init:
  #      mode: always
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artrend?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ssafy
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    # ??? ????? ???? ??? ??
    register-with-eureka: true
    # ??? ????? ?????? ??? ????? ????
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


