server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jg6735/spring-cloud-config
          username: jg6735
          password: wlrmschlrh2

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh